/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author god
 */
public class MessageComponent extends javax.swing.JPanel {

    /**
     * Creates new form MessageComponent
     */
    public MessageComponent(String message, boolean isReceiver) {
        initComponents();
        messageTextArea.setText(message);
        if (isReceiver) {
            this.add(messageTextArea);
            this.add(fillerPanel);
        } else {
            this.add(fillerPanel);
            this.add(messageTextArea);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageTextArea = new javax.swing.JTextArea();
        fillerPanel = new javax.swing.JPanel();

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        messageTextArea.setFocusable(false);
        messageTextArea.setVerifyInputWhenFocusTarget(false);

        fillerPanel.setDoubleBuffered(false);
        fillerPanel.setFocusable(false);
        fillerPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        fillerPanel.setOpaque(false);
        fillerPanel.setRequestFocusEnabled(false);
        fillerPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout fillerPanelLayout = new javax.swing.GroupLayout(fillerPanel);
        fillerPanel.setLayout(fillerPanelLayout);
        fillerPanelLayout.setHorizontalGroup(
            fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        fillerPanelLayout.setVerticalGroup(
            fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(2147483647, 100));
        setMinimumSize(new java.awt.Dimension(13, 100));
        setPreferredSize(new java.awt.Dimension(200, 100));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new java.awt.GridLayout(1, 2));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fillerPanel;
    private javax.swing.JTextArea messageTextArea;
    // End of variables declaration//GEN-END:variables
}
