/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

import shared.client.Message;

/**
 *
 * @author god
 */
public class MessageComponent extends javax.swing.JPanel {

    /**
     * Creates new form MessageComponent
     */
    public MessageComponent(Message message, boolean isReceiver) {
        initComponents();
        saveFileButton.setVisible(false);
        this.message = message;
        messageTextArea.setText(message.getMessage());
        senderNameLabel.setText(message.getSenderName());

        if (isReceiver) {
            this.add(messagePanel);
            this.add(fillerPanel);
        } else {
            this.add(fillerPanel);
            this.add(messagePanel);
        }
    }

    public MessageComponent(Message message, JFileChooser fileChooser, ScreenRoot root, byte[] bytes) {
        this(message, true);
        saveFileButton.setEnabled(true);
        saveFileButton.setVisible(true);

        saveFileButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                if (fileChooser.showSaveDialog(root) == JFileChooser.APPROVE_OPTION) {
                    File file = fileChooser.getSelectedFile();
                    try {
                        Files.write(file.toPath(), bytes);
                        saveFileButton.setEnabled(false);
                        saveFileButton.setText("saved");
                    } catch (IOException e) {
                        System.err.println("File can't be saved: " + e.toString());
                    }
                }

            }
        });
    }

    public Message getMessage() {
        return message;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fillerPanel = new javax.swing.JPanel();
        messagePanel = new javax.swing.JPanel();
        senderNameLabel = new javax.swing.JLabel();
        saveFileButton = new javax.swing.JButton();
        messageTextArea = new javax.swing.JTextArea();

        fillerPanel.setDoubleBuffered(false);
        fillerPanel.setFocusable(false);
        fillerPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        fillerPanel.setOpaque(false);
        fillerPanel.setRequestFocusEnabled(false);
        fillerPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout fillerPanelLayout = new javax.swing.GroupLayout(fillerPanel);
        fillerPanel.setLayout(fillerPanelLayout);
        fillerPanelLayout.setHorizontalGroup(
                fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));
        fillerPanelLayout.setVerticalGroup(
                fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        senderNameLabel.setText("jLabel1");

        saveFileButton.setText("save");
        saveFileButton.setEnabled(false);

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        messageTextArea.setFocusable(false);
        messageTextArea.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(messagePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(messagePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(messageTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 313,
                                                Short.MAX_VALUE)
                                        .addGroup(messagePanelLayout.createSequentialGroup()
                                                .addComponent(senderNameLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(saveFileButton)))
                                .addContainerGap()));
        messagePanelLayout.setVerticalGroup(
                messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(messagePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(senderNameLabel)
                                        .addComponent(saveFileButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(messageTextArea, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(2147483647, 100));
        setMinimumSize(new java.awt.Dimension(13, 100));
        setPreferredSize(new java.awt.Dimension(200, 100));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new java.awt.GridLayout(1, 2));
    }// </editor-fold>//GEN-END:initComponents

    private Message message;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fillerPanel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JLabel senderNameLabel;
    // End of variables declaration//GEN-END:variables
}
