package gui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;

import shared.client.User;
import shared.communication.Action;
import shared.communication.Client;
import shared.communication.Sender;

/**
 *
 * @author god
 */
public class ScreenAuthentication extends javax.swing.JPanel {

    /**
     * Creates new form Authentication
     */
    public ScreenAuthentication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TextFieldSignInName = new javax.swing.JTextField();
        LabelSignInName = new javax.swing.JLabel();
        PasswordSignIn = new javax.swing.JPasswordField();
        LabelSignInPassword = new javax.swing.JLabel();
        ButtonSignIn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        TextFieldSignUpName = new javax.swing.JTextField();
        LabelSignUpName = new javax.swing.JLabel();
        PasswordSignUp = new javax.swing.JPasswordField();
        LabelSignUpPassword = new javax.swing.JLabel();
        ButtonSignUp = new javax.swing.JButton();
        RepeatPasswordSignUp = new javax.swing.JPasswordField();
        LabelSignUpRepeatPassword = new javax.swing.JLabel();

        TextFieldSignInName.setText("jTextField1");
        TextFieldSignInName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSignInNameActionPerformed(evt);
            }
        });

        LabelSignInName.setText("Nome");

        PasswordSignIn.setText("jPasswordField1");
        PasswordSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSignInActionPerformed(evt);
            }
        });

        LabelSignInPassword.setText("Senha");

        ButtonSignIn.setText("Logar");
        ButtonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSignInName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSignInPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(TextFieldSignInName))))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSignInName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSignInName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSignInPassword))
                .addGap(18, 18, 18)
                .addComponent(ButtonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sign In", jPanel1);

        TextFieldSignUpName.setText("jTextField1");
        TextFieldSignUpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSignUpNameActionPerformed(evt);
            }
        });

        LabelSignUpName.setText("Nome");

        PasswordSignUp.setText("jPasswordField1");
        PasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordSignUpActionPerformed(evt);
            }
        });

        LabelSignUpPassword.setText("Senha");

        ButtonSignUp.setText("Criar Conta");
        ButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignUpActionPerformed(evt);
            }
        });

        RepeatPasswordSignUp.setText("jPasswordField1");
        RepeatPasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatPasswordSignUpActionPerformed(evt);
            }
        });

        LabelSignUpRepeatPassword.setText("Repita senha");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelSignUpRepeatPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RepeatPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonSignUp)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSignUpName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSignUpPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(TextFieldSignUpName))))
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSignUpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSignUpName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSignUpPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RepeatPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSignUpRepeatPassword))
                .addGap(18, 18, 18)
                .addComponent(ButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sign Up", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldSignInNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSignInNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSignInNameActionPerformed

    private void ButtonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignInActionPerformed
        String name = TextFieldSignInName.getText();
        String password = new String(PasswordSignIn.getPassword());
    }//GEN-LAST:event_ButtonSignInActionPerformed

    private void PasswordSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordSignInActionPerformed

    private void TextFieldSignUpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSignUpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSignUpNameActionPerformed

    private void PasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordSignUpActionPerformed

    private void ButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignUpActionPerformed
        String name = TextFieldSignInName.getText();
        String password = new String(PasswordSignIn.getPassword());
        User user = new User(name, password);
        Sender<User> sender = new Sender<User>(name, name, Action.CREATE_ACCOUNT);
        sender.appendData(user);

        Socket socket = ScreenRoot.getSocket();

        try {
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
            out.writeObject(sender);
        } catch (IOException e) {
            System.err.println(e);
        }



    }//GEN-LAST:event_ButtonSignUpActionPerformed

    private void RepeatPasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatPasswordSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeatPasswordSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSignIn;
    private javax.swing.JButton ButtonSignUp;
    private javax.swing.JLabel LabelSignInName;
    private javax.swing.JLabel LabelSignInPassword;
    private javax.swing.JLabel LabelSignUpName;
    private javax.swing.JLabel LabelSignUpPassword;
    private javax.swing.JLabel LabelSignUpRepeatPassword;
    private javax.swing.JPasswordField PasswordSignIn;
    private javax.swing.JPasswordField PasswordSignUp;
    private javax.swing.JPasswordField RepeatPasswordSignUp;
    private javax.swing.JTextField TextFieldSignInName;
    private javax.swing.JTextField TextFieldSignUpName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
