package shared.communication;

public enum Action {
    SEND_USER2USER,
    SEND_USER2GROUP,
    SEND_FILE2USER,

    ADD_USER_CONTACT,
    GET_ALL_USER_CONTACTS,

    GET_GROUP_MESSAGES,
    GET_USER_MESSAGES,

    CREATE_GROUP,
    LEAVE_GROUP,
    DELETE_GROUP,
    ADD_USER2GROUP,
    REMOVE_USER_FROM_GROUP,
    RENAME_GROUP,

    CREATE_ACCOUNT,
    SIGN_IN,
    NONE
}
