package shared.communication;

public enum Action {
    SEND_USER2USER,
    SEND_USER2GROUP,

    ADD_USER_CONTACT,
    GET_ALL_USER_CONTACTS,

    GET_USER_MESSAGES,
    GET_GROUP_MESSAGES,
    GET_ALL_USER_MESSAGES,
    GET_ALL_GROUP_MESSAGES,
    GET_MESSAGES,

    CREATE_ACCOUNT,
    SIGN_IN,
    NONE
}
